spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "authorization"